using System.Globalization;
using System.Net;
using System.Text;
using Tdm.Core.Manifest;

namespace Tdm.Observability.Reports;

/// <summary>Inputs the renderer cannot derive from the manifest alone (W4-D1). Everything is
/// optional — <c>HtmlReport.Render(manifest)</c> with defaults is a complete report.</summary>
public sealed class HtmlReportOptions
{
    /// <summary>Outcome message of a checksum/signature verification of the manifest file
    /// (`ManifestSigner.Verify`). Null → "not verified" is shown; verification needs the
    /// file + side files, which a pure render over an in-memory manifest doesn't have.</summary>
    public string? SignatureStatus { get; set; }

    /// <summary>Prior runs from a W3-D7 trend store (any order; sorted by StartedUtc before
    /// use). Non-empty → the report gains benchmark sparklines against this history.</summary>
    public IReadOnlyList<RunManifest> TrendHistory { get; set; } = [];

    /// <summary>Stat charted in the trend sparklines: meanMs | p50Ms | p95Ms | maxMs | totalMs.</summary>
    public string TrendStat { get; set; } = "p95Ms";

    /// <summary>Creates of the same entity in one scenario at or above this count collapse
    /// into one aggregate lineage node (bulk operations always aggregate).</summary>
    public int BulkAggregationThreshold { get; set; } = 10;
}

/// <summary>
/// The living-doc HTML report (W4-D1): a pure function over <see cref="RunManifest"/> that
/// renders one **self-contained** file — inline CSS, inline SVG, no scripts, no external
/// requests — usable as a CI artifact or an email attachment. Same posture as the W1-D3
/// emitters; `tdm report` and `--report html=…` are the CLI entry points.
/// </summary>
public static class HtmlReport
{
    public static string Render(RunManifest manifest, HtmlReportOptions? options = null)
    {
        options ??= new HtmlReportOptions();
        var html = new StringBuilder();
        html.Append("<!DOCTYPE html><html lang=\"en\"><head><meta charset=\"utf-8\">");
        html.Append("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">");
        html.Append($"<title>TDM run — {E(manifest.Run.Name)}</title>");
        html.Append("<style>").Append(Css).Append("</style></head><body>");

        RenderHeader(html, manifest, options);
        RenderScenarios(html, manifest);

        html.Append("<section><h2>Reference lineage</h2>");
        html.Append("<p class=\"hint\">Entities as nodes, references as edges — an arrow points from the entity that holds the reference to the entity it resolved to.</p>");
        html.Append(LineageGraph.RenderSvg(manifest, options.BulkAggregationThreshold));
        html.Append("</section>");

        RenderBenchmarks(html, manifest);
        RenderTrends(html, manifest, options);

        html.Append("<footer>Generated by TDM ").Append(E(manifest.Run.TdmVersion))
            .Append(" from the run manifest — the manifest, not this report, is the audit artifact.</footer>");
        html.Append("</body></html>");
        return html.ToString();
    }

    // ---------------------------------------------------------------- header

    private static void RenderHeader(StringBuilder html, RunManifest manifest, HtmlReportOptions options)
    {
        var run = manifest.Run;
        html.Append("<header><h1>").Append(E(run.Name)).Append("</h1>");
        html.Append("<div class=\"badges\">");
        html.Append(OutcomeBadge(run.Outcome.ToString()));
        if (run.DryRun) html.Append("<span class=\"badge neutral\">dry run</span>");
        if (run.Environment is { Length: > 0 } env) html.Append($"<span class=\"badge neutral\">env: {E(env)}</span>");
        if (run.PolicyOverrideApplied) html.Append("<span class=\"badge warn\">policy override applied</span>");
        html.Append("</div>");

        html.Append("<dl class=\"facts\">");
        Fact(html, "Started (UTC)", run.StartedUtc.ToString("yyyy-MM-dd HH:mm:ss", CultureInfo.InvariantCulture));
        Fact(html, "Duration", Ms(run.DurationMs));
        Fact(html, "Lifecycle", run.Lifecycle.ToString());
        Fact(html, "Failure policy", run.FailurePolicy.ToString());
        Fact(html, "Versions", $"tdm {run.TdmVersion} · Bogus {run.BogusVersion} · EF {run.EfVersion} · identity contract {run.IdentityContractVersion}");
        Fact(html, "Runner", run.Attribution.RunnerId.Length > 0 ? $"{run.Attribution.RunnerId} on {run.Attribution.Hostname}" : "-");
        if (run.Attribution.GitSha is { Length: > 0 } sha)
            Fact(html, "Git", sha[..Math.Min(12, sha.Length)] + (run.Attribution.GitDirty == true ? " (dirty)" : ""));
        if (run.Attribution.SettingsFileSha256 is { Length: > 0 } settingsSha)
            Fact(html, "Settings SHA-256", settingsSha[..Math.Min(12, settingsSha.Length)] + "…");
        if (run.Attribution.ResumedFrom is { Length: > 0 } resumed)
            Fact(html, "Resumed from", resumed);
        if (run.RegistryRunId is { Length: > 0 } registryRun)
            Fact(html, "Registry run", registryRun);
        Fact(html, "Attestation", run.Attestation.SyntheticOnly
            ? $"synthetic only ({string.Join(", ", run.Attestation.Sources)})"
            : "NOT synthetic-only — see attestation sources");
        Fact(html, "Signature", options.SignatureStatus ?? "not verified (report rendered without the manifest file's checksum/signature)");
        if (run.PluginPackages.Count > 0)
            Fact(html, "Plugins", string.Join(" · ", run.PluginPackages.Select(p => $"{p.Key}@{p.Value}")));
        html.Append("</dl>");

        if (run.PolicyViolations.Count > 0)
        {
            html.Append($"<div class=\"panel {(run.PolicyOverrideApplied ? "warn" : "fail")}\"><strong>")
                .Append(run.PolicyViolations.Count.ToString(CultureInfo.InvariantCulture))
                .Append(" policy violation(s)")
                .Append(run.PolicyOverrideApplied ? " — overridden via --approval" : " — the run refused to start")
                .Append("</strong><ul>");
            foreach (var violation in run.PolicyViolations)
                html.Append($"<li><code>{E(violation.Rule)}</code> {E(violation.Message)}</li>");
            html.Append("</ul></div>");
        }

        if (manifest.Teardown.Deleted > 0 || manifest.Teardown.Orphaned.Count > 0)
        {
            html.Append($"<p class=\"hint\">Teardown: {manifest.Teardown.Deleted} deleted");
            if (manifest.Teardown.Orphaned.Count > 0)
                html.Append($", <strong>{manifest.Teardown.Orphaned.Count} orphaned</strong>");
            html.Append("</p>");
        }
        html.Append("</header>");
    }

    // ---------------------------------------------------------------- scenarios

    private static void RenderScenarios(StringBuilder html, RunManifest manifest)
    {
        html.Append("<section><h2>Scenarios</h2>");
        foreach (var feature in manifest.Scenarios.GroupBy(s => s.Feature))
        {
            html.Append($"<h3>{E(feature.Key)}</h3>");
            foreach (var scenario in feature) RenderScenario(html, scenario);
        }
        if (manifest.Scenarios.Count == 0) html.Append("<p class=\"empty\">No scenarios were executed.</p>");
        html.Append("</section>");
    }

    private static void RenderScenario(StringBuilder html, ScenarioManifest scenario)
    {
        var duration = scenario.Entities.Sum(e => e.DurationMs) + scenario.BulkOperations.Sum(b => b.DurationMs);
        html.Append("<details class=\"scenario\"><summary>");
        html.Append(OutcomeBadge(scenario.Outcome.ToString()));
        html.Append($"<span class=\"scenario-name\">{E(scenario.Scenario)}</span>");
        html.Append("<span class=\"scenario-meta\">");
        html.Append($"seed {scenario.Seed.ToString(CultureInfo.InvariantCulture)} · {scenario.Lifecycle}");
        if (scenario.Tags.Count > 0) html.Append($" · {E(string.Join(" ", scenario.Tags.Select(t => "@" + t)))}");
        html.Append($" · {scenario.Entities.Count.ToString(CultureInfo.InvariantCulture)} entit{(scenario.Entities.Count == 1 ? "y" : "ies")}");
        if (scenario.Warnings.Count > 0 || scenario.UnmatchedSteps.Count > 0)
            html.Append($" · <strong>{(scenario.Warnings.Count + scenario.UnmatchedSteps.Count).ToString(CultureInfo.InvariantCulture)} warning(s)</strong>");
        html.Append($" · {Ms(duration)}</span></summary>");

        foreach (var step in scenario.UnmatchedSteps)
            html.Append($"<p class=\"warning\">Unmatched step (line {step.Line.ToString(CultureInfo.InvariantCulture)}): {E(step.Text)}</p>");
        foreach (var warning in scenario.Warnings)
            html.Append($"<p class=\"warning\">{E(warning)}</p>");

        if (scenario.BulkOperations.Count > 0)
        {
            html.Append("<table><thead><tr><th>bulk create</th><th>requested</th><th>persisted</th><th>failed</th><th>mode</th><th>sampled</th><th>hashed</th><th>values sha-256</th><th>duration</th></tr></thead><tbody>");
            foreach (var bulk in scenario.BulkOperations)
            {
                html.Append("<tr>")
                    .Append($"<td>{E(bulk.Domain)}.{E(bulk.Entity)}</td>")
                    .Append($"<td class=\"num\">{bulk.Requested.ToString(CultureInfo.InvariantCulture)}</td>")
                    .Append($"<td class=\"num\">{bulk.Count.ToString(CultureInfo.InvariantCulture)}</td>")
                    .Append($"<td class=\"num\">{bulk.Failed.ToString(CultureInfo.InvariantCulture)}</td>")
                    .Append($"<td>{bulk.Mode}</td>")
                    .Append($"<td class=\"num\">{bulk.SampledRows.ToString(CultureInfo.InvariantCulture)}</td>")
                    .Append($"<td class=\"num\">{bulk.HashedRows.ToString(CultureInfo.InvariantCulture)}</td>")
                    .Append($"<td><code>{E(Shorten(bulk.ValuesSha256))}</code></td>")
                    .Append($"<td class=\"num\">{Ms(bulk.DurationMs)}</td></tr>");
            }
            html.Append("</tbody></table>");
        }

        if (scenario.Entities.Count > 0)
        {
            html.Append("<table><thead><tr><th>#</th><th>entity</th><th>verb</th><th>domain</th><th>id</th><th>natural key</th><th>persisted via</th><th>faker</th><th>duration</th></tr></thead><tbody>");
            foreach (var entity in scenario.Entities)
            {
                html.Append("<tr>")
                    .Append($"<td class=\"num\">{entity.Ordinal.ToString(CultureInfo.InvariantCulture)}</td>")
                    .Append($"<td>{RenderEntityValues(entity)}</td>")
                    .Append($"<td>{E(entity.Verb)}</td>")
                    .Append($"<td>{E(entity.Domain)}</td>")
                    .Append($"<td><code>{E(Shorten(entity.Id))}</code></td>")
                    .Append($"<td>{E(entity.NaturalKey ?? "-")}</td>")
                    .Append($"<td>{E(entity.PersistedVia ?? "-")}</td>")
                    .Append($"<td>{E(entity.FakerSource ?? "-")}</td>")
                    .Append($"<td class=\"num\">{Ms(entity.DurationMs)}</td></tr>");
                foreach (var warning in entity.Warnings)
                    html.Append($"<tr><td></td><td colspan=\"8\" class=\"warning\">{E(warning)}</td></tr>");
            }
            html.Append("</tbody></table>");
        }

        if (scenario.References.Count > 0)
        {
            html.Append("<table><thead><tr><th>line</th><th>source #</th><th>reference target</th><th>resolved from</th><th>id</th><th>owning domain</th><th>verify</th></tr></thead><tbody>");
            foreach (var reference in scenario.References)
            {
                html.Append("<tr>")
                    .Append($"<td class=\"num\">{reference.Step.ToString(CultureInfo.InvariantCulture)}</td>")
                    .Append($"<td class=\"num\">{(reference.SourceOrdinal is { } so ? so.ToString(CultureInfo.InvariantCulture) : "-")}</td>")
                    .Append($"<td>{E(reference.Target)}</td>")
                    .Append($"<td>{E(reference.ResolvedFrom)}</td>")
                    .Append($"<td><code>{E(Shorten(reference.Id))}</code></td>")
                    .Append($"<td>{E(reference.OwningDomain ?? "-")}</td>")
                    .Append($"<td>{E(reference.VerifyOutcome ?? "-")}</td></tr>");
            }
            html.Append("</tbody></table>");
        }

        if (scenario.Teardown is { } teardown)
        {
            html.Append($"<p class=\"hint\">Scenario teardown: {teardown.Deleted.ToString(CultureInfo.InvariantCulture)} deleted");
            if (teardown.Orphaned.Count > 0)
                html.Append($", <strong>{teardown.Orphaned.Count.ToString(CultureInfo.InvariantCulture)} orphaned</strong>: {E(string.Join("; ", teardown.Orphaned))}");
            html.Append("</p>");
        }
        html.Append("</details>");
    }

    /// <summary>Entity name expanding to its full final values, with applied overrides marked —
    /// the per-entity drill-down the handoff asks for (§2.1).</summary>
    private static string RenderEntityValues(EntityManifest entity)
    {
        if (entity.Values.Count == 0) return E(entity.Entity);
        var details = new StringBuilder($"<details class=\"values\"><summary>{E(entity.Entity)}</summary><dl>");
        foreach (var (name, value) in entity.Values)
        {
            var overridden = entity.OverridesApplied.Contains(name, StringComparer.OrdinalIgnoreCase);
            details.Append($"<dt>{E(name)}{(overridden ? "<span class=\"badge override\">override</span>" : "")}</dt>")
                .Append($"<dd>{(value is null ? "<em>null</em>" : E(value))}</dd>");
        }
        return details.Append("</dl></details>").ToString();
    }

    // ---------------------------------------------------------------- benchmarks

    private static void RenderBenchmarks(StringBuilder html, RunManifest manifest)
    {
        if (manifest.Run.Benchmark.Count == 0) return;
        html.Append("<section><h2>Benchmarks</h2>");
        html.Append("<p class=\"hint\">Per operation and per operation:entity — p50 (solid) and p95 (pale), scaled to the slowest p95.</p>");
        RenderBenchmarkTable(html, manifest.Run.Benchmark);
        html.Append("</section>");
    }

    private static void RenderBenchmarkTable(StringBuilder html, Dictionary<string, BenchmarkStats> benchmark)
    {
        var max = Math.Max(0.001, benchmark.Values.Max(s => s.P95Ms));
        html.Append("<table class=\"bench\"><thead><tr><th>operation</th><th>count</th><th>p50</th><th>p95</th><th>max</th><th></th></tr></thead><tbody>");
        foreach (var (key, stats) in benchmark.OrderBy(b => b.Key, StringComparer.Ordinal))
        {
            html.Append("<tr>")
                .Append($"<td>{E(key)}</td>")
                .Append($"<td class=\"num\">{stats.Count.ToString(CultureInfo.InvariantCulture)}</td>")
                .Append($"<td class=\"num\">{Ms(stats.P50Ms)}</td>")
                .Append($"<td class=\"num\">{Ms(stats.P95Ms)}</td>")
                .Append($"<td class=\"num\">{Ms(stats.MaxMs)}</td>")
                .Append("<td class=\"bar-cell\">")
                .Append(FormattableString.Invariant($"<span class=\"bar p95\" style=\"width:{stats.P95Ms / max * 100:0.#}%\"></span>"))
                .Append(FormattableString.Invariant($"<span class=\"bar p50\" style=\"width:{stats.P50Ms / max * 100:0.#}%\"></span>"))
                .Append("</td></tr>");
        }
        html.Append("</tbody></table>");
    }

    // ---------------------------------------------------------------- trends

    private static void RenderTrends(StringBuilder html, RunManifest manifest, HtmlReportOptions options)
    {
        if (options.TrendHistory.Count == 0) return;

        var stat = StatSelector(options.TrendStat);
        var history = options.TrendHistory
            .Where(m => m.Run.StartedUtc != manifest.Run.StartedUtc || m.Run.Name != manifest.Run.Name)
            .OrderBy(m => m.Run.StartedUtc)
            .ToList();

        html.Append("<section><h2>Trends</h2>");
        html.Append($"<p class=\"hint\">{E(options.TrendStat)} across the last {history.Count.ToString(CultureInfo.InvariantCulture)} stored run(s) (oldest → newest), ending at this run. Δ compares this run to the median of the stored history — the W3-D8 rolling-baseline posture.</p>");
        html.Append("<table><thead><tr><th>operation</th><th>trend</th><th>baseline (median)</th><th>this run</th><th>Δ</th></tr></thead><tbody>");

        RenderTrendRow(html, "run duration",
            [.. history.Select(m => (double?)m.Run.DurationMs)], manifest.Run.DurationMs);

        foreach (var key in manifest.Run.Benchmark.Keys.OrderBy(k => k, StringComparer.Ordinal))
        {
            var series = history
                .Select(m => m.Run.Benchmark.TryGetValue(key, out var s) ? (double?)stat(s) : null)
                .ToList();
            RenderTrendRow(html, key, series, stat(manifest.Run.Benchmark[key]));
        }
        html.Append("</tbody></table></section>");
    }

    private static void RenderTrendRow(StringBuilder html, string label, List<double?> history, double current)
    {
        var known = history.Where(v => v.HasValue).Select(v => v!.Value).ToList();
        var baseline = Median(known);
        var delta = baseline is > 0 ? (current - baseline.Value) / baseline.Value * 100 : (double?)null;
        html.Append("<tr>")
            .Append($"<td>{E(label)}</td>")
            .Append($"<td>{Sparkline([.. history, current])}</td>")
            .Append($"<td class=\"num\">{(baseline is { } b ? Ms(b) : "-")}</td>")
            .Append($"<td class=\"num\">{Ms(current)}</td>")
            .Append(delta is { } pct
                ? FormattableString.Invariant($"<td class=\"num {(pct > 5 ? "worse" : pct < -5 ? "better" : "")}\">{(pct >= 0 ? "+" : "")}{pct:0.#}%</td>")
                : "<td class=\"num\">-</td>")
            .Append("</tr>");
    }

    /// <summary>Inline SVG sparkline; the final (current-run) point is emphasised. Null gaps
    /// (runs that lack the stat) are skipped, keeping the x spacing honest.</summary>
    private static string Sparkline(List<double?> series)
    {
        const int width = 140, height = 30, pad = 3;
        var known = series.Where(v => v.HasValue).Select(v => v!.Value).ToList();
        if (known.Count == 0) return "";
        var min = known.Min();
        var max = known.Max();
        var range = Math.Max(1e-9, max - min);

        var points = new List<(double X, double Y)>();
        for (var i = 0; i < series.Count; i++)
        {
            if (series[i] is not { } value) continue;
            var x = series.Count == 1 ? width / 2d : pad + i * (width - 2d * pad) / (series.Count - 1);
            var y = height - pad - (value - min) / range * (height - 2d * pad);
            points.Add((x, y));
        }

        var svg = new StringBuilder(FormattableString.Invariant(
            $"<svg class=\"spark\" viewBox=\"0 0 {width} {height}\" role=\"img\" aria-label=\"trend sparkline\">"));
        if (points.Count > 1)
        {
            svg.Append("<polyline fill=\"none\" points=\"")
                .Append(string.Join(' ', points.Select(p => FormattableString.Invariant($"{p.X:0.#},{p.Y:0.#}"))))
                .Append("\"/>");
        }
        var last = points[^1];
        svg.Append(FormattableString.Invariant($"<circle cx=\"{last.X:0.#}\" cy=\"{last.Y:0.#}\" r=\"2.5\"/>"));
        return svg.Append("</svg>").ToString();
    }

    private static Func<BenchmarkStats, double> StatSelector(string stat) => stat.ToLowerInvariant() switch
    {
        "meanms" => s => s.MeanMs,
        "p50ms" => s => s.P50Ms,
        "maxms" => s => s.MaxMs,
        "totalms" => s => s.TotalMs,
        _ => s => s.P95Ms,
    };

    private static double? Median(List<double> values)
    {
        if (values.Count == 0) return null;
        var sorted = values.OrderBy(v => v).ToList();
        var mid = sorted.Count / 2;
        return sorted.Count % 2 == 1 ? sorted[mid] : (sorted[mid - 1] + sorted[mid]) / 2;
    }

    // ---------------------------------------------------------------- helpers

    private static void Fact(StringBuilder html, string term, string value) =>
        html.Append($"<dt>{E(term)}</dt><dd>{E(value)}</dd>");

    private static string OutcomeBadge(string outcome)
    {
        var cls = outcome switch
        {
            "Succeeded" => "ok",
            "CompletedWithWarnings" => "warn",
            "Skipped" => "neutral",
            _ => "fail",
        };
        return $"<span class=\"badge {cls}\">{E(outcome)}</span>";
    }

    private static string Ms(double ms) => ms >= 10_000
        ? FormattableString.Invariant($"{ms / 1000:0.##} s")
        : FormattableString.Invariant($"{ms:0.#} ms");

    private static string Shorten(string? value) =>
        value is null ? "-" : value.Length <= 13 ? value : value[..12] + "…";

    private static string E(string? text) => WebUtility.HtmlEncode(text ?? "");

    private const string Css = """
        :root { --bg: #ffffff; --fg: #1c2430; --muted: #5b6774; --line: #d9dee5; --panel: #f4f6f8;
                --ok: #1a7f37; --warn: #9a6700; --fail: #cf222e; --accent: #0969da;
                --ctx: #0969da; --db: #8250df; --idc: #1a7f37; }
        @media (prefers-color-scheme: dark) {
          :root { --bg: #0d1117; --fg: #e6edf3; --muted: #9198a1; --line: #30363d; --panel: #161b22;
                  --ok: #3fb950; --warn: #d29922; --fail: #f85149; --accent: #4493f8;
                  --ctx: #4493f8; --db: #ab7df8; --idc: #3fb950; } }
        * { box-sizing: border-box; }
        body { margin: 0 auto; padding: 24px; max-width: 1100px; background: var(--bg); color: var(--fg);
               font: 14px/1.5 system-ui, -apple-system, "Segoe UI", sans-serif; }
        h1 { font-size: 22px; margin: 0 0 8px; } h2 { font-size: 17px; margin: 28px 0 8px; }
        h3 { font-size: 14px; margin: 16px 0 6px; color: var(--muted); }
        code { font: 12px/1.4 ui-monospace, Consolas, monospace; }
        footer { margin-top: 32px; color: var(--muted); font-size: 12px; border-top: 1px solid var(--line); padding-top: 8px; }
        .hint, .empty { color: var(--muted); font-size: 13px; }
        .badges { display: flex; gap: 6px; flex-wrap: wrap; margin-bottom: 12px; }
        .badge { display: inline-block; padding: 1px 8px; border-radius: 10px; font-size: 12px; font-weight: 600;
                 border: 1px solid var(--line); }
        .badge.ok { color: var(--ok); border-color: var(--ok); }
        .badge.warn { color: var(--warn); border-color: var(--warn); }
        .badge.fail { color: var(--fail); border-color: var(--fail); }
        .badge.neutral { color: var(--muted); }
        .badge.override { margin-left: 6px; color: var(--accent); border-color: var(--accent); font-weight: 400; }
        .facts { display: grid; grid-template-columns: max-content 1fr; gap: 2px 16px; margin: 0; }
        .facts dt { color: var(--muted); } .facts dd { margin: 0; overflow-wrap: anywhere; }
        .panel { border: 1px solid var(--line); border-left: 4px solid var(--fail); background: var(--panel);
                 border-radius: 6px; padding: 10px 14px; margin: 12px 0; }
        .panel.warn { border-left-color: var(--warn); }
        .panel ul { margin: 6px 0 0; padding-left: 20px; }
        details.scenario { border: 1px solid var(--line); border-radius: 6px; margin: 8px 0; background: var(--panel); }
        details.scenario > summary { cursor: pointer; padding: 8px 12px; display: flex; gap: 10px; align-items: baseline; flex-wrap: wrap; }
        details.scenario[open] > summary { border-bottom: 1px solid var(--line); }
        details.scenario > :not(summary) { margin: 10px 12px; }
        .scenario-name { font-weight: 600; } .scenario-meta { color: var(--muted); font-size: 12px; }
        details.values > summary { cursor: pointer; }
        details.values dl { display: grid; grid-template-columns: max-content 1fr; gap: 1px 12px; margin: 6px 0 4px 14px; font-size: 12px; }
        details.values dt { color: var(--muted); } details.values dd { margin: 0; overflow-wrap: anywhere; }
        table { border-collapse: collapse; width: 100%; font-size: 13px; background: var(--bg); }
        th, td { text-align: left; padding: 4px 10px; border-bottom: 1px solid var(--line); vertical-align: top; }
        th { color: var(--muted); font-weight: 600; font-size: 12px; }
        td.num { text-align: right; font-variant-numeric: tabular-nums; white-space: nowrap; }
        td.worse { color: var(--fail); font-weight: 600; } td.better { color: var(--ok); }
        .warning { color: var(--warn); margin: 4px 0; }
        .bar-cell { width: 30%; min-width: 140px; position: relative; }
        .bar { display: block; height: 5px; border-radius: 3px; margin: 2px 0; }
        .bar.p50 { background: var(--accent); } .bar.p95 { background: var(--accent); opacity: .35; }
        .lineage-scroll { overflow-x: auto; border: 1px solid var(--line); border-radius: 6px; background: var(--panel); padding: 8px; }
        svg.lineage { display: block; min-width: 100%; }
        .lineage .node rect { fill: var(--bg); stroke-width: 1.5; }
        .lineage .node.external rect { stroke-dasharray: 4 3; fill: var(--panel); }
        .lineage .node-title { font: 600 12px system-ui, sans-serif; fill: var(--fg); }
        .lineage .node-sub { font: 11px system-ui, sans-serif; fill: var(--muted); }
        .lineage .edge { fill: none; stroke-width: 1.5; }
        .lineage .edge-label { font: 10px system-ui, sans-serif; }
        .lineage .edge.edge-ctx, .legend-line.edge-ctx { stroke: var(--ctx); } .lineage text.edge-ctx { fill: var(--ctx); }
        .lineage .edge.edge-db, .legend-line.edge-db { stroke: var(--db); } .lineage text.edge-db { fill: var(--db); }
        .lineage .edge.edge-idc, .legend-line.edge-idc { stroke: var(--idc); } .lineage text.edge-idc { fill: var(--idc); }
        .lineage .edge.edge-other { stroke: var(--muted); } .lineage text.edge-other { fill: var(--muted); }
        .lineage .arrow-head { fill: var(--muted); }
        .lineage .dom-0 rect { stroke: #0969da; } .lineage .dom-1 rect { stroke: #8250df; }
        .lineage .dom-2 rect { stroke: #1a7f37; } .lineage .dom-3 rect { stroke: #9a6700; }
        .lineage .dom-4 rect { stroke: #cf222e; } .lineage .dom-5 rect { stroke: #1b7c83; }
        .lineage .dom-6 rect { stroke: #bf3989; } .lineage .dom-7 rect { stroke: #57606a; }
        .lineage .dom-none rect { stroke: var(--muted); }
        .legend { display: flex; gap: 16px; flex-wrap: wrap; margin-top: 6px; font-size: 12px; color: var(--muted); }
        .legend-item { display: inline-flex; align-items: center; gap: 5px; }
        .legend-line { display: inline-block; width: 18px; height: 0; border-top: 2px solid; }
        .legend-line.edge-ctx { border-color: var(--ctx); } .legend-line.edge-db { border-color: var(--db); }
        .legend-line.edge-idc { border-color: var(--idc); }
        .legend-swatch { display: inline-block; width: 10px; height: 10px; border-radius: 3px; border: 2px solid var(--muted); }
        .legend-swatch.external { border-style: dashed; }
        .legend-swatch.dom-0 { border-color: #0969da; } .legend-swatch.dom-1 { border-color: #8250df; }
        .legend-swatch.dom-2 { border-color: #1a7f37; } .legend-swatch.dom-3 { border-color: #9a6700; }
        .legend-swatch.dom-4 { border-color: #cf222e; } .legend-swatch.dom-5 { border-color: #1b7c83; }
        .legend-swatch.dom-6 { border-color: #bf3989; } .legend-swatch.dom-7 { border-color: #57606a; }
        svg.spark { width: 140px; height: 30px; }
        svg.spark polyline { stroke: var(--accent); stroke-width: 1.5; }
        svg.spark circle { fill: var(--accent); }
        @media print { details.scenario { break-inside: avoid; } details[open] > summary { border-bottom: 1px solid var(--line); } }
        """;
}
